services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eventreservas
      MYSQL_ROOT_HOST: "%"  # <- Permite conexiones remotas sin contraseña
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # <- Permite que root no tenga contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
